// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package store

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/qinquanliuxiang666/alertmanager/model"
)

func newAlertSendRecord(db *gorm.DB, opts ...gen.DOOption) alertSendRecord {
	_alertSendRecord := alertSendRecord{}

	_alertSendRecord.alertSendRecordDo.UseDB(db, opts...)
	_alertSendRecord.alertSendRecordDo.UseModel(&model.AlertSendRecord{})

	tableName := _alertSendRecord.alertSendRecordDo.TableName()
	_alertSendRecord.ALL = field.NewAsterisk(tableName)
	_alertSendRecord.ID = field.NewInt(tableName, "id")
	_alertSendRecord.CreatedAt = field.NewTime(tableName, "created_at")
	_alertSendRecord.UpdatedAt = field.NewTime(tableName, "updated_at")
	_alertSendRecord.SendStatus = field.NewString(tableName, "send_status")
	_alertSendRecord.ErrorMessage = field.NewString(tableName, "error_message")
	_alertSendRecord.ExternalMessageID = field.NewString(tableName, "external_message_id")
	_alertSendRecord.AlertHistory = alertSendRecordHasManyAlertHistory{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("AlertHistory", "model.AlertHistory"),
		AlertChannel: struct {
			field.RelationField
			AlertTemplate struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("AlertHistory.AlertChannel", "model.AlertChannel"),
			AlertTemplate: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("AlertHistory.AlertChannel.AlertTemplate", "model.AlertTemplate"),
			},
		},
		AlertSendRecord: struct {
			field.RelationField
			AlertHistory struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("AlertHistory.AlertSendRecord", "model.AlertSendRecord"),
			AlertHistory: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("AlertHistory.AlertSendRecord.AlertHistory", "model.AlertHistory"),
			},
		},
		AlertSilence: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("AlertHistory.AlertSilence", "model.AlertSilence"),
		},
	}

	_alertSendRecord.fillFieldMap()

	return _alertSendRecord
}

type alertSendRecord struct {
	alertSendRecordDo

	ALL               field.Asterisk
	ID                field.Int
	CreatedAt         field.Time
	UpdatedAt         field.Time
	SendStatus        field.String // 发送状态(success, failed)
	ErrorMessage      field.String // 如果发送失败，记录失败的报错详情(供排查)
	ExternalMessageID field.String // 第三方平台返回的消息ID(如飞书的 message_id)
	AlertHistory      alertSendRecordHasManyAlertHistory

	fieldMap map[string]field.Expr
}

func (a alertSendRecord) Table(newTableName string) *alertSendRecord {
	a.alertSendRecordDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a alertSendRecord) As(alias string) *alertSendRecord {
	a.alertSendRecordDo.DO = *(a.alertSendRecordDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *alertSendRecord) updateTableName(table string) *alertSendRecord {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.SendStatus = field.NewString(table, "send_status")
	a.ErrorMessage = field.NewString(table, "error_message")
	a.ExternalMessageID = field.NewString(table, "external_message_id")

	a.fillFieldMap()

	return a
}

func (a *alertSendRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *alertSendRecord) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 7)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["send_status"] = a.SendStatus
	a.fieldMap["error_message"] = a.ErrorMessage
	a.fieldMap["external_message_id"] = a.ExternalMessageID

}

func (a alertSendRecord) clone(db *gorm.DB) alertSendRecord {
	a.alertSendRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	a.AlertHistory.db = db.Session(&gorm.Session{Initialized: true})
	a.AlertHistory.db.Statement.ConnPool = db.Statement.ConnPool
	return a
}

func (a alertSendRecord) replaceDB(db *gorm.DB) alertSendRecord {
	a.alertSendRecordDo.ReplaceDB(db)
	a.AlertHistory.db = db.Session(&gorm.Session{})
	return a
}

type alertSendRecordHasManyAlertHistory struct {
	db *gorm.DB

	field.RelationField

	AlertChannel struct {
		field.RelationField
		AlertTemplate struct {
			field.RelationField
		}
	}
	AlertSendRecord struct {
		field.RelationField
		AlertHistory struct {
			field.RelationField
		}
	}
	AlertSilence struct {
		field.RelationField
	}
}

func (a alertSendRecordHasManyAlertHistory) Where(conds ...field.Expr) *alertSendRecordHasManyAlertHistory {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a alertSendRecordHasManyAlertHistory) WithContext(ctx context.Context) *alertSendRecordHasManyAlertHistory {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a alertSendRecordHasManyAlertHistory) Session(session *gorm.Session) *alertSendRecordHasManyAlertHistory {
	a.db = a.db.Session(session)
	return &a
}

func (a alertSendRecordHasManyAlertHistory) Model(m *model.AlertSendRecord) *alertSendRecordHasManyAlertHistoryTx {
	return &alertSendRecordHasManyAlertHistoryTx{a.db.Model(m).Association(a.Name())}
}

func (a alertSendRecordHasManyAlertHistory) Unscoped() *alertSendRecordHasManyAlertHistory {
	a.db = a.db.Unscoped()
	return &a
}

type alertSendRecordHasManyAlertHistoryTx struct{ tx *gorm.Association }

func (a alertSendRecordHasManyAlertHistoryTx) Find() (result []*model.AlertHistory, err error) {
	return result, a.tx.Find(&result)
}

func (a alertSendRecordHasManyAlertHistoryTx) Append(values ...*model.AlertHistory) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a alertSendRecordHasManyAlertHistoryTx) Replace(values ...*model.AlertHistory) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a alertSendRecordHasManyAlertHistoryTx) Delete(values ...*model.AlertHistory) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a alertSendRecordHasManyAlertHistoryTx) Clear() error {
	return a.tx.Clear()
}

func (a alertSendRecordHasManyAlertHistoryTx) Count() int64 {
	return a.tx.Count()
}

func (a alertSendRecordHasManyAlertHistoryTx) Unscoped() *alertSendRecordHasManyAlertHistoryTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type alertSendRecordDo struct{ gen.DO }

type IAlertSendRecordDo interface {
	gen.SubQuery
	Debug() IAlertSendRecordDo
	WithContext(ctx context.Context) IAlertSendRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAlertSendRecordDo
	WriteDB() IAlertSendRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAlertSendRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAlertSendRecordDo
	Not(conds ...gen.Condition) IAlertSendRecordDo
	Or(conds ...gen.Condition) IAlertSendRecordDo
	Select(conds ...field.Expr) IAlertSendRecordDo
	Where(conds ...gen.Condition) IAlertSendRecordDo
	Order(conds ...field.Expr) IAlertSendRecordDo
	Distinct(cols ...field.Expr) IAlertSendRecordDo
	Omit(cols ...field.Expr) IAlertSendRecordDo
	Join(table schema.Tabler, on ...field.Expr) IAlertSendRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAlertSendRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAlertSendRecordDo
	Group(cols ...field.Expr) IAlertSendRecordDo
	Having(conds ...gen.Condition) IAlertSendRecordDo
	Limit(limit int) IAlertSendRecordDo
	Offset(offset int) IAlertSendRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAlertSendRecordDo
	Unscoped() IAlertSendRecordDo
	Create(values ...*model.AlertSendRecord) error
	CreateInBatches(values []*model.AlertSendRecord, batchSize int) error
	Save(values ...*model.AlertSendRecord) error
	First() (*model.AlertSendRecord, error)
	Take() (*model.AlertSendRecord, error)
	Last() (*model.AlertSendRecord, error)
	Find() ([]*model.AlertSendRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AlertSendRecord, err error)
	FindInBatches(result *[]*model.AlertSendRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AlertSendRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAlertSendRecordDo
	Assign(attrs ...field.AssignExpr) IAlertSendRecordDo
	Joins(fields ...field.RelationField) IAlertSendRecordDo
	Preload(fields ...field.RelationField) IAlertSendRecordDo
	FirstOrInit() (*model.AlertSendRecord, error)
	FirstOrCreate() (*model.AlertSendRecord, error)
	FindByPage(offset int, limit int) (result []*model.AlertSendRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAlertSendRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a alertSendRecordDo) Debug() IAlertSendRecordDo {
	return a.withDO(a.DO.Debug())
}

func (a alertSendRecordDo) WithContext(ctx context.Context) IAlertSendRecordDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a alertSendRecordDo) ReadDB() IAlertSendRecordDo {
	return a.Clauses(dbresolver.Read)
}

func (a alertSendRecordDo) WriteDB() IAlertSendRecordDo {
	return a.Clauses(dbresolver.Write)
}

func (a alertSendRecordDo) Session(config *gorm.Session) IAlertSendRecordDo {
	return a.withDO(a.DO.Session(config))
}

func (a alertSendRecordDo) Clauses(conds ...clause.Expression) IAlertSendRecordDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a alertSendRecordDo) Returning(value interface{}, columns ...string) IAlertSendRecordDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a alertSendRecordDo) Not(conds ...gen.Condition) IAlertSendRecordDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a alertSendRecordDo) Or(conds ...gen.Condition) IAlertSendRecordDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a alertSendRecordDo) Select(conds ...field.Expr) IAlertSendRecordDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a alertSendRecordDo) Where(conds ...gen.Condition) IAlertSendRecordDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a alertSendRecordDo) Order(conds ...field.Expr) IAlertSendRecordDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a alertSendRecordDo) Distinct(cols ...field.Expr) IAlertSendRecordDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a alertSendRecordDo) Omit(cols ...field.Expr) IAlertSendRecordDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a alertSendRecordDo) Join(table schema.Tabler, on ...field.Expr) IAlertSendRecordDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a alertSendRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAlertSendRecordDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a alertSendRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) IAlertSendRecordDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a alertSendRecordDo) Group(cols ...field.Expr) IAlertSendRecordDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a alertSendRecordDo) Having(conds ...gen.Condition) IAlertSendRecordDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a alertSendRecordDo) Limit(limit int) IAlertSendRecordDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a alertSendRecordDo) Offset(offset int) IAlertSendRecordDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a alertSendRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAlertSendRecordDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a alertSendRecordDo) Unscoped() IAlertSendRecordDo {
	return a.withDO(a.DO.Unscoped())
}

func (a alertSendRecordDo) Create(values ...*model.AlertSendRecord) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a alertSendRecordDo) CreateInBatches(values []*model.AlertSendRecord, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a alertSendRecordDo) Save(values ...*model.AlertSendRecord) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a alertSendRecordDo) First() (*model.AlertSendRecord, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertSendRecord), nil
	}
}

func (a alertSendRecordDo) Take() (*model.AlertSendRecord, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertSendRecord), nil
	}
}

func (a alertSendRecordDo) Last() (*model.AlertSendRecord, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertSendRecord), nil
	}
}

func (a alertSendRecordDo) Find() ([]*model.AlertSendRecord, error) {
	result, err := a.DO.Find()
	return result.([]*model.AlertSendRecord), err
}

func (a alertSendRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AlertSendRecord, err error) {
	buf := make([]*model.AlertSendRecord, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a alertSendRecordDo) FindInBatches(result *[]*model.AlertSendRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a alertSendRecordDo) Attrs(attrs ...field.AssignExpr) IAlertSendRecordDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a alertSendRecordDo) Assign(attrs ...field.AssignExpr) IAlertSendRecordDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a alertSendRecordDo) Joins(fields ...field.RelationField) IAlertSendRecordDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a alertSendRecordDo) Preload(fields ...field.RelationField) IAlertSendRecordDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a alertSendRecordDo) FirstOrInit() (*model.AlertSendRecord, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertSendRecord), nil
	}
}

func (a alertSendRecordDo) FirstOrCreate() (*model.AlertSendRecord, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertSendRecord), nil
	}
}

func (a alertSendRecordDo) FindByPage(offset int, limit int) (result []*model.AlertSendRecord, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a alertSendRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a alertSendRecordDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a alertSendRecordDo) Delete(models ...*model.AlertSendRecord) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *alertSendRecordDo) withDO(do gen.Dao) *alertSendRecordDo {
	a.DO = *do.(*gen.DO)
	return a
}
