// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package store

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/qinquanliuxiang666/alertmanager/model"
)

func newAlertChannel(db *gorm.DB, opts ...gen.DOOption) alertChannel {
	_alertChannel := alertChannel{}

	_alertChannel.alertChannelDo.UseDB(db, opts...)
	_alertChannel.alertChannelDo.UseModel(&model.AlertChannel{})

	tableName := _alertChannel.alertChannelDo.TableName()
	_alertChannel.ALL = field.NewAsterisk(tableName)
	_alertChannel.ID = field.NewInt(tableName, "id")
	_alertChannel.CreatedAt = field.NewTime(tableName, "created_at")
	_alertChannel.UpdatedAt = field.NewTime(tableName, "updated_at")
	_alertChannel.DeletedAt = field.NewField(tableName, "deleted_at")
	_alertChannel.Name = field.NewString(tableName, "name")
	_alertChannel.Type = field.NewString(tableName, "type")
	_alertChannel.Status = field.NewInt(tableName, "status")
	_alertChannel.AggregationStatus = field.NewInt(tableName, "aggregation_status")
	_alertChannel.Config = field.NewField(tableName, "config")
	_alertChannel.Description = field.NewString(tableName, "description")
	_alertChannel.AlertTemplateID = field.NewInt(tableName, "alert_template_id")
	_alertChannel.AlertTemplate = alertChannelBelongsToAlertTemplate{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("AlertTemplate", "model.AlertTemplate"),
	}

	_alertChannel.fillFieldMap()

	return _alertChannel
}

type alertChannel struct {
	alertChannelDo

	ALL               field.Asterisk
	ID                field.Int // 主键ID
	CreatedAt         field.Time
	UpdatedAt         field.Time
	DeletedAt         field.Field
	Name              field.String // 告警渠道名称(如: SRE团队钉钉群)
	Type              field.String // 渠道类型(feishuApp/feishuBoot/webhook)
	Status            field.Int    // 状态(0-停用, 1-启用)
	AggregationStatus field.Int    // 状态(0-停用, 1-启用)
	Config            field.Field  // 渠道动态配置(JSON格式)
	Description       field.String // 描述与备注
	AlertTemplateID   field.Int    // 绑定的告警模板ID
	AlertTemplate     alertChannelBelongsToAlertTemplate

	fieldMap map[string]field.Expr
}

func (a alertChannel) Table(newTableName string) *alertChannel {
	a.alertChannelDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a alertChannel) As(alias string) *alertChannel {
	a.alertChannelDo.DO = *(a.alertChannelDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *alertChannel) updateTableName(table string) *alertChannel {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewField(table, "deleted_at")
	a.Name = field.NewString(table, "name")
	a.Type = field.NewString(table, "type")
	a.Status = field.NewInt(table, "status")
	a.AggregationStatus = field.NewInt(table, "aggregation_status")
	a.Config = field.NewField(table, "config")
	a.Description = field.NewString(table, "description")
	a.AlertTemplateID = field.NewInt(table, "alert_template_id")

	a.fillFieldMap()

	return a
}

func (a *alertChannel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *alertChannel) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 12)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["name"] = a.Name
	a.fieldMap["type"] = a.Type
	a.fieldMap["status"] = a.Status
	a.fieldMap["aggregation_status"] = a.AggregationStatus
	a.fieldMap["config"] = a.Config
	a.fieldMap["description"] = a.Description
	a.fieldMap["alert_template_id"] = a.AlertTemplateID

}

func (a alertChannel) clone(db *gorm.DB) alertChannel {
	a.alertChannelDo.ReplaceConnPool(db.Statement.ConnPool)
	a.AlertTemplate.db = db.Session(&gorm.Session{Initialized: true})
	a.AlertTemplate.db.Statement.ConnPool = db.Statement.ConnPool
	return a
}

func (a alertChannel) replaceDB(db *gorm.DB) alertChannel {
	a.alertChannelDo.ReplaceDB(db)
	a.AlertTemplate.db = db.Session(&gorm.Session{})
	return a
}

type alertChannelBelongsToAlertTemplate struct {
	db *gorm.DB

	field.RelationField
}

func (a alertChannelBelongsToAlertTemplate) Where(conds ...field.Expr) *alertChannelBelongsToAlertTemplate {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a alertChannelBelongsToAlertTemplate) WithContext(ctx context.Context) *alertChannelBelongsToAlertTemplate {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a alertChannelBelongsToAlertTemplate) Session(session *gorm.Session) *alertChannelBelongsToAlertTemplate {
	a.db = a.db.Session(session)
	return &a
}

func (a alertChannelBelongsToAlertTemplate) Model(m *model.AlertChannel) *alertChannelBelongsToAlertTemplateTx {
	return &alertChannelBelongsToAlertTemplateTx{a.db.Model(m).Association(a.Name())}
}

func (a alertChannelBelongsToAlertTemplate) Unscoped() *alertChannelBelongsToAlertTemplate {
	a.db = a.db.Unscoped()
	return &a
}

type alertChannelBelongsToAlertTemplateTx struct{ tx *gorm.Association }

func (a alertChannelBelongsToAlertTemplateTx) Find() (result *model.AlertTemplate, err error) {
	return result, a.tx.Find(&result)
}

func (a alertChannelBelongsToAlertTemplateTx) Append(values ...*model.AlertTemplate) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a alertChannelBelongsToAlertTemplateTx) Replace(values ...*model.AlertTemplate) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a alertChannelBelongsToAlertTemplateTx) Delete(values ...*model.AlertTemplate) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a alertChannelBelongsToAlertTemplateTx) Clear() error {
	return a.tx.Clear()
}

func (a alertChannelBelongsToAlertTemplateTx) Count() int64 {
	return a.tx.Count()
}

func (a alertChannelBelongsToAlertTemplateTx) Unscoped() *alertChannelBelongsToAlertTemplateTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type alertChannelDo struct{ gen.DO }

type IAlertChannelDo interface {
	gen.SubQuery
	Debug() IAlertChannelDo
	WithContext(ctx context.Context) IAlertChannelDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAlertChannelDo
	WriteDB() IAlertChannelDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAlertChannelDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAlertChannelDo
	Not(conds ...gen.Condition) IAlertChannelDo
	Or(conds ...gen.Condition) IAlertChannelDo
	Select(conds ...field.Expr) IAlertChannelDo
	Where(conds ...gen.Condition) IAlertChannelDo
	Order(conds ...field.Expr) IAlertChannelDo
	Distinct(cols ...field.Expr) IAlertChannelDo
	Omit(cols ...field.Expr) IAlertChannelDo
	Join(table schema.Tabler, on ...field.Expr) IAlertChannelDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAlertChannelDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAlertChannelDo
	Group(cols ...field.Expr) IAlertChannelDo
	Having(conds ...gen.Condition) IAlertChannelDo
	Limit(limit int) IAlertChannelDo
	Offset(offset int) IAlertChannelDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAlertChannelDo
	Unscoped() IAlertChannelDo
	Create(values ...*model.AlertChannel) error
	CreateInBatches(values []*model.AlertChannel, batchSize int) error
	Save(values ...*model.AlertChannel) error
	First() (*model.AlertChannel, error)
	Take() (*model.AlertChannel, error)
	Last() (*model.AlertChannel, error)
	Find() ([]*model.AlertChannel, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AlertChannel, err error)
	FindInBatches(result *[]*model.AlertChannel, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AlertChannel) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAlertChannelDo
	Assign(attrs ...field.AssignExpr) IAlertChannelDo
	Joins(fields ...field.RelationField) IAlertChannelDo
	Preload(fields ...field.RelationField) IAlertChannelDo
	FirstOrInit() (*model.AlertChannel, error)
	FirstOrCreate() (*model.AlertChannel, error)
	FindByPage(offset int, limit int) (result []*model.AlertChannel, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAlertChannelDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a alertChannelDo) Debug() IAlertChannelDo {
	return a.withDO(a.DO.Debug())
}

func (a alertChannelDo) WithContext(ctx context.Context) IAlertChannelDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a alertChannelDo) ReadDB() IAlertChannelDo {
	return a.Clauses(dbresolver.Read)
}

func (a alertChannelDo) WriteDB() IAlertChannelDo {
	return a.Clauses(dbresolver.Write)
}

func (a alertChannelDo) Session(config *gorm.Session) IAlertChannelDo {
	return a.withDO(a.DO.Session(config))
}

func (a alertChannelDo) Clauses(conds ...clause.Expression) IAlertChannelDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a alertChannelDo) Returning(value interface{}, columns ...string) IAlertChannelDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a alertChannelDo) Not(conds ...gen.Condition) IAlertChannelDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a alertChannelDo) Or(conds ...gen.Condition) IAlertChannelDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a alertChannelDo) Select(conds ...field.Expr) IAlertChannelDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a alertChannelDo) Where(conds ...gen.Condition) IAlertChannelDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a alertChannelDo) Order(conds ...field.Expr) IAlertChannelDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a alertChannelDo) Distinct(cols ...field.Expr) IAlertChannelDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a alertChannelDo) Omit(cols ...field.Expr) IAlertChannelDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a alertChannelDo) Join(table schema.Tabler, on ...field.Expr) IAlertChannelDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a alertChannelDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAlertChannelDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a alertChannelDo) RightJoin(table schema.Tabler, on ...field.Expr) IAlertChannelDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a alertChannelDo) Group(cols ...field.Expr) IAlertChannelDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a alertChannelDo) Having(conds ...gen.Condition) IAlertChannelDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a alertChannelDo) Limit(limit int) IAlertChannelDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a alertChannelDo) Offset(offset int) IAlertChannelDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a alertChannelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAlertChannelDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a alertChannelDo) Unscoped() IAlertChannelDo {
	return a.withDO(a.DO.Unscoped())
}

func (a alertChannelDo) Create(values ...*model.AlertChannel) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a alertChannelDo) CreateInBatches(values []*model.AlertChannel, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a alertChannelDo) Save(values ...*model.AlertChannel) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a alertChannelDo) First() (*model.AlertChannel, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertChannel), nil
	}
}

func (a alertChannelDo) Take() (*model.AlertChannel, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertChannel), nil
	}
}

func (a alertChannelDo) Last() (*model.AlertChannel, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertChannel), nil
	}
}

func (a alertChannelDo) Find() ([]*model.AlertChannel, error) {
	result, err := a.DO.Find()
	return result.([]*model.AlertChannel), err
}

func (a alertChannelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AlertChannel, err error) {
	buf := make([]*model.AlertChannel, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a alertChannelDo) FindInBatches(result *[]*model.AlertChannel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a alertChannelDo) Attrs(attrs ...field.AssignExpr) IAlertChannelDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a alertChannelDo) Assign(attrs ...field.AssignExpr) IAlertChannelDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a alertChannelDo) Joins(fields ...field.RelationField) IAlertChannelDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a alertChannelDo) Preload(fields ...field.RelationField) IAlertChannelDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a alertChannelDo) FirstOrInit() (*model.AlertChannel, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertChannel), nil
	}
}

func (a alertChannelDo) FirstOrCreate() (*model.AlertChannel, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertChannel), nil
	}
}

func (a alertChannelDo) FindByPage(offset int, limit int) (result []*model.AlertChannel, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a alertChannelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a alertChannelDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a alertChannelDo) Delete(models ...*model.AlertChannel) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *alertChannelDo) withDO(do gen.Dao) *alertChannelDo {
	a.DO = *do.(*gen.DO)
	return a
}
