// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package store

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/qinquanliuxiang666/alertmanager/model"
)

func newAlertHistory(db *gorm.DB, opts ...gen.DOOption) alertHistory {
	_alertHistory := alertHistory{}

	_alertHistory.alertHistoryDo.UseDB(db, opts...)
	_alertHistory.alertHistoryDo.UseModel(&model.AlertHistory{})

	tableName := _alertHistory.alertHistoryDo.TableName()
	_alertHistory.ALL = field.NewAsterisk(tableName)
	_alertHistory.ID = field.NewInt(tableName, "id")
	_alertHistory.Cluster = field.NewString(tableName, "cluster")
	_alertHistory.CreatedAt = field.NewTime(tableName, "created_at")
	_alertHistory.Fingerprint = field.NewString(tableName, "fingerprint")
	_alertHistory.StartsAt = field.NewTime(tableName, "starts_at")
	_alertHistory.EndsAt = field.NewTime(tableName, "ends_at")
	_alertHistory.Status = field.NewString(tableName, "status")
	_alertHistory.Alertname = field.NewString(tableName, "alertname")
	_alertHistory.Severity = field.NewString(tableName, "severity")
	_alertHistory.Instance = field.NewString(tableName, "instance")
	_alertHistory.Labels = field.NewField(tableName, "labels")
	_alertHistory.Annotations = field.NewField(tableName, "annotations")
	_alertHistory.AlertChannelID = field.NewInt(tableName, "alert_channel_id")
	_alertHistory.AlertSendRecordID = field.NewInt(tableName, "alert_send_record_id")
	_alertHistory.SendCount = field.NewInt(tableName, "send_count")
	_alertHistory.IsSilenced = field.NewBool(tableName, "is_silenced")
	_alertHistory.AlertSilenceID = field.NewInt(tableName, "alert_silence_id")
	_alertHistory.AlertChannel = alertHistoryBelongsToAlertChannel{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("AlertChannel", "model.AlertChannel"),
		AlertTemplate: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("AlertChannel.AlertTemplate", "model.AlertTemplate"),
		},
	}

	_alertHistory.AlertSendRecord = alertHistoryBelongsToAlertSendRecord{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("AlertSendRecord", "model.AlertSendRecord"),
		AlertHistory: struct {
			field.RelationField
			AlertChannel struct {
				field.RelationField
			}
			AlertSendRecord struct {
				field.RelationField
			}
			AlertSilence struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("AlertSendRecord.AlertHistory", "model.AlertHistory"),
			AlertChannel: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("AlertSendRecord.AlertHistory.AlertChannel", "model.AlertChannel"),
			},
			AlertSendRecord: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("AlertSendRecord.AlertHistory.AlertSendRecord", "model.AlertSendRecord"),
			},
			AlertSilence: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("AlertSendRecord.AlertHistory.AlertSilence", "model.AlertSilence"),
			},
		},
	}

	_alertHistory.AlertSilence = alertHistoryBelongsToAlertSilence{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("AlertSilence", "model.AlertSilence"),
	}

	_alertHistory.fillFieldMap()

	return _alertHistory
}

type alertHistory struct {
	alertHistoryDo

	ALL               field.Asterisk
	ID                field.Int    // 主键ID
	Cluster           field.String // 租户
	CreatedAt         field.Time   // 本条记录存入数据库的时间
	Fingerprint       field.String // 指纹
	StartsAt          field.Time   // 开始时间
	EndsAt            field.Time   // 告警恢复时间(未恢复则为NULL)
	Status            field.String // 告警状态(如: firing, resolved)
	Alertname         field.String // 告警名称
	Severity          field.String // 告警级别(如: critical, warning, info)
	Instance          field.String // 告警发生的实例(如IP或主机名)
	Labels            field.Field  // 告警标签集合
	Annotations       field.Field  // 告警详情/注解
	AlertChannelID    field.Int    // 关联的告警发送通道ID
	AlertSendRecordID field.Int    // 关联的告警发送记录ID
	SendCount         field.Int    // 告警发送次数
	IsSilenced        field.Bool   // 是否被静默
	AlertSilenceID    field.Int    // 关联的静默规则ID
	AlertChannel      alertHistoryBelongsToAlertChannel

	AlertSendRecord alertHistoryBelongsToAlertSendRecord

	AlertSilence alertHistoryBelongsToAlertSilence

	fieldMap map[string]field.Expr
}

func (a alertHistory) Table(newTableName string) *alertHistory {
	a.alertHistoryDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a alertHistory) As(alias string) *alertHistory {
	a.alertHistoryDo.DO = *(a.alertHistoryDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *alertHistory) updateTableName(table string) *alertHistory {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt(table, "id")
	a.Cluster = field.NewString(table, "cluster")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.Fingerprint = field.NewString(table, "fingerprint")
	a.StartsAt = field.NewTime(table, "starts_at")
	a.EndsAt = field.NewTime(table, "ends_at")
	a.Status = field.NewString(table, "status")
	a.Alertname = field.NewString(table, "alertname")
	a.Severity = field.NewString(table, "severity")
	a.Instance = field.NewString(table, "instance")
	a.Labels = field.NewField(table, "labels")
	a.Annotations = field.NewField(table, "annotations")
	a.AlertChannelID = field.NewInt(table, "alert_channel_id")
	a.AlertSendRecordID = field.NewInt(table, "alert_send_record_id")
	a.SendCount = field.NewInt(table, "send_count")
	a.IsSilenced = field.NewBool(table, "is_silenced")
	a.AlertSilenceID = field.NewInt(table, "alert_silence_id")

	a.fillFieldMap()

	return a
}

func (a *alertHistory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *alertHistory) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 20)
	a.fieldMap["id"] = a.ID
	a.fieldMap["cluster"] = a.Cluster
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["fingerprint"] = a.Fingerprint
	a.fieldMap["starts_at"] = a.StartsAt
	a.fieldMap["ends_at"] = a.EndsAt
	a.fieldMap["status"] = a.Status
	a.fieldMap["alertname"] = a.Alertname
	a.fieldMap["severity"] = a.Severity
	a.fieldMap["instance"] = a.Instance
	a.fieldMap["labels"] = a.Labels
	a.fieldMap["annotations"] = a.Annotations
	a.fieldMap["alert_channel_id"] = a.AlertChannelID
	a.fieldMap["alert_send_record_id"] = a.AlertSendRecordID
	a.fieldMap["send_count"] = a.SendCount
	a.fieldMap["is_silenced"] = a.IsSilenced
	a.fieldMap["alert_silence_id"] = a.AlertSilenceID

}

func (a alertHistory) clone(db *gorm.DB) alertHistory {
	a.alertHistoryDo.ReplaceConnPool(db.Statement.ConnPool)
	a.AlertChannel.db = db.Session(&gorm.Session{Initialized: true})
	a.AlertChannel.db.Statement.ConnPool = db.Statement.ConnPool
	a.AlertSendRecord.db = db.Session(&gorm.Session{Initialized: true})
	a.AlertSendRecord.db.Statement.ConnPool = db.Statement.ConnPool
	a.AlertSilence.db = db.Session(&gorm.Session{Initialized: true})
	a.AlertSilence.db.Statement.ConnPool = db.Statement.ConnPool
	return a
}

func (a alertHistory) replaceDB(db *gorm.DB) alertHistory {
	a.alertHistoryDo.ReplaceDB(db)
	a.AlertChannel.db = db.Session(&gorm.Session{})
	a.AlertSendRecord.db = db.Session(&gorm.Session{})
	a.AlertSilence.db = db.Session(&gorm.Session{})
	return a
}

type alertHistoryBelongsToAlertChannel struct {
	db *gorm.DB

	field.RelationField

	AlertTemplate struct {
		field.RelationField
	}
}

func (a alertHistoryBelongsToAlertChannel) Where(conds ...field.Expr) *alertHistoryBelongsToAlertChannel {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a alertHistoryBelongsToAlertChannel) WithContext(ctx context.Context) *alertHistoryBelongsToAlertChannel {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a alertHistoryBelongsToAlertChannel) Session(session *gorm.Session) *alertHistoryBelongsToAlertChannel {
	a.db = a.db.Session(session)
	return &a
}

func (a alertHistoryBelongsToAlertChannel) Model(m *model.AlertHistory) *alertHistoryBelongsToAlertChannelTx {
	return &alertHistoryBelongsToAlertChannelTx{a.db.Model(m).Association(a.Name())}
}

func (a alertHistoryBelongsToAlertChannel) Unscoped() *alertHistoryBelongsToAlertChannel {
	a.db = a.db.Unscoped()
	return &a
}

type alertHistoryBelongsToAlertChannelTx struct{ tx *gorm.Association }

func (a alertHistoryBelongsToAlertChannelTx) Find() (result *model.AlertChannel, err error) {
	return result, a.tx.Find(&result)
}

func (a alertHistoryBelongsToAlertChannelTx) Append(values ...*model.AlertChannel) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a alertHistoryBelongsToAlertChannelTx) Replace(values ...*model.AlertChannel) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a alertHistoryBelongsToAlertChannelTx) Delete(values ...*model.AlertChannel) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a alertHistoryBelongsToAlertChannelTx) Clear() error {
	return a.tx.Clear()
}

func (a alertHistoryBelongsToAlertChannelTx) Count() int64 {
	return a.tx.Count()
}

func (a alertHistoryBelongsToAlertChannelTx) Unscoped() *alertHistoryBelongsToAlertChannelTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type alertHistoryBelongsToAlertSendRecord struct {
	db *gorm.DB

	field.RelationField

	AlertHistory struct {
		field.RelationField
		AlertChannel struct {
			field.RelationField
		}
		AlertSendRecord struct {
			field.RelationField
		}
		AlertSilence struct {
			field.RelationField
		}
	}
}

func (a alertHistoryBelongsToAlertSendRecord) Where(conds ...field.Expr) *alertHistoryBelongsToAlertSendRecord {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a alertHistoryBelongsToAlertSendRecord) WithContext(ctx context.Context) *alertHistoryBelongsToAlertSendRecord {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a alertHistoryBelongsToAlertSendRecord) Session(session *gorm.Session) *alertHistoryBelongsToAlertSendRecord {
	a.db = a.db.Session(session)
	return &a
}

func (a alertHistoryBelongsToAlertSendRecord) Model(m *model.AlertHistory) *alertHistoryBelongsToAlertSendRecordTx {
	return &alertHistoryBelongsToAlertSendRecordTx{a.db.Model(m).Association(a.Name())}
}

func (a alertHistoryBelongsToAlertSendRecord) Unscoped() *alertHistoryBelongsToAlertSendRecord {
	a.db = a.db.Unscoped()
	return &a
}

type alertHistoryBelongsToAlertSendRecordTx struct{ tx *gorm.Association }

func (a alertHistoryBelongsToAlertSendRecordTx) Find() (result *model.AlertSendRecord, err error) {
	return result, a.tx.Find(&result)
}

func (a alertHistoryBelongsToAlertSendRecordTx) Append(values ...*model.AlertSendRecord) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a alertHistoryBelongsToAlertSendRecordTx) Replace(values ...*model.AlertSendRecord) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a alertHistoryBelongsToAlertSendRecordTx) Delete(values ...*model.AlertSendRecord) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a alertHistoryBelongsToAlertSendRecordTx) Clear() error {
	return a.tx.Clear()
}

func (a alertHistoryBelongsToAlertSendRecordTx) Count() int64 {
	return a.tx.Count()
}

func (a alertHistoryBelongsToAlertSendRecordTx) Unscoped() *alertHistoryBelongsToAlertSendRecordTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type alertHistoryBelongsToAlertSilence struct {
	db *gorm.DB

	field.RelationField
}

func (a alertHistoryBelongsToAlertSilence) Where(conds ...field.Expr) *alertHistoryBelongsToAlertSilence {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a alertHistoryBelongsToAlertSilence) WithContext(ctx context.Context) *alertHistoryBelongsToAlertSilence {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a alertHistoryBelongsToAlertSilence) Session(session *gorm.Session) *alertHistoryBelongsToAlertSilence {
	a.db = a.db.Session(session)
	return &a
}

func (a alertHistoryBelongsToAlertSilence) Model(m *model.AlertHistory) *alertHistoryBelongsToAlertSilenceTx {
	return &alertHistoryBelongsToAlertSilenceTx{a.db.Model(m).Association(a.Name())}
}

func (a alertHistoryBelongsToAlertSilence) Unscoped() *alertHistoryBelongsToAlertSilence {
	a.db = a.db.Unscoped()
	return &a
}

type alertHistoryBelongsToAlertSilenceTx struct{ tx *gorm.Association }

func (a alertHistoryBelongsToAlertSilenceTx) Find() (result *model.AlertSilence, err error) {
	return result, a.tx.Find(&result)
}

func (a alertHistoryBelongsToAlertSilenceTx) Append(values ...*model.AlertSilence) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a alertHistoryBelongsToAlertSilenceTx) Replace(values ...*model.AlertSilence) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a alertHistoryBelongsToAlertSilenceTx) Delete(values ...*model.AlertSilence) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a alertHistoryBelongsToAlertSilenceTx) Clear() error {
	return a.tx.Clear()
}

func (a alertHistoryBelongsToAlertSilenceTx) Count() int64 {
	return a.tx.Count()
}

func (a alertHistoryBelongsToAlertSilenceTx) Unscoped() *alertHistoryBelongsToAlertSilenceTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type alertHistoryDo struct{ gen.DO }

type IAlertHistoryDo interface {
	gen.SubQuery
	Debug() IAlertHistoryDo
	WithContext(ctx context.Context) IAlertHistoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAlertHistoryDo
	WriteDB() IAlertHistoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAlertHistoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAlertHistoryDo
	Not(conds ...gen.Condition) IAlertHistoryDo
	Or(conds ...gen.Condition) IAlertHistoryDo
	Select(conds ...field.Expr) IAlertHistoryDo
	Where(conds ...gen.Condition) IAlertHistoryDo
	Order(conds ...field.Expr) IAlertHistoryDo
	Distinct(cols ...field.Expr) IAlertHistoryDo
	Omit(cols ...field.Expr) IAlertHistoryDo
	Join(table schema.Tabler, on ...field.Expr) IAlertHistoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAlertHistoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAlertHistoryDo
	Group(cols ...field.Expr) IAlertHistoryDo
	Having(conds ...gen.Condition) IAlertHistoryDo
	Limit(limit int) IAlertHistoryDo
	Offset(offset int) IAlertHistoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAlertHistoryDo
	Unscoped() IAlertHistoryDo
	Create(values ...*model.AlertHistory) error
	CreateInBatches(values []*model.AlertHistory, batchSize int) error
	Save(values ...*model.AlertHistory) error
	First() (*model.AlertHistory, error)
	Take() (*model.AlertHistory, error)
	Last() (*model.AlertHistory, error)
	Find() ([]*model.AlertHistory, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AlertHistory, err error)
	FindInBatches(result *[]*model.AlertHistory, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AlertHistory) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAlertHistoryDo
	Assign(attrs ...field.AssignExpr) IAlertHistoryDo
	Joins(fields ...field.RelationField) IAlertHistoryDo
	Preload(fields ...field.RelationField) IAlertHistoryDo
	FirstOrInit() (*model.AlertHistory, error)
	FirstOrCreate() (*model.AlertHistory, error)
	FindByPage(offset int, limit int) (result []*model.AlertHistory, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAlertHistoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a alertHistoryDo) Debug() IAlertHistoryDo {
	return a.withDO(a.DO.Debug())
}

func (a alertHistoryDo) WithContext(ctx context.Context) IAlertHistoryDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a alertHistoryDo) ReadDB() IAlertHistoryDo {
	return a.Clauses(dbresolver.Read)
}

func (a alertHistoryDo) WriteDB() IAlertHistoryDo {
	return a.Clauses(dbresolver.Write)
}

func (a alertHistoryDo) Session(config *gorm.Session) IAlertHistoryDo {
	return a.withDO(a.DO.Session(config))
}

func (a alertHistoryDo) Clauses(conds ...clause.Expression) IAlertHistoryDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a alertHistoryDo) Returning(value interface{}, columns ...string) IAlertHistoryDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a alertHistoryDo) Not(conds ...gen.Condition) IAlertHistoryDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a alertHistoryDo) Or(conds ...gen.Condition) IAlertHistoryDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a alertHistoryDo) Select(conds ...field.Expr) IAlertHistoryDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a alertHistoryDo) Where(conds ...gen.Condition) IAlertHistoryDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a alertHistoryDo) Order(conds ...field.Expr) IAlertHistoryDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a alertHistoryDo) Distinct(cols ...field.Expr) IAlertHistoryDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a alertHistoryDo) Omit(cols ...field.Expr) IAlertHistoryDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a alertHistoryDo) Join(table schema.Tabler, on ...field.Expr) IAlertHistoryDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a alertHistoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAlertHistoryDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a alertHistoryDo) RightJoin(table schema.Tabler, on ...field.Expr) IAlertHistoryDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a alertHistoryDo) Group(cols ...field.Expr) IAlertHistoryDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a alertHistoryDo) Having(conds ...gen.Condition) IAlertHistoryDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a alertHistoryDo) Limit(limit int) IAlertHistoryDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a alertHistoryDo) Offset(offset int) IAlertHistoryDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a alertHistoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAlertHistoryDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a alertHistoryDo) Unscoped() IAlertHistoryDo {
	return a.withDO(a.DO.Unscoped())
}

func (a alertHistoryDo) Create(values ...*model.AlertHistory) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a alertHistoryDo) CreateInBatches(values []*model.AlertHistory, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a alertHistoryDo) Save(values ...*model.AlertHistory) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a alertHistoryDo) First() (*model.AlertHistory, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertHistory), nil
	}
}

func (a alertHistoryDo) Take() (*model.AlertHistory, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertHistory), nil
	}
}

func (a alertHistoryDo) Last() (*model.AlertHistory, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertHistory), nil
	}
}

func (a alertHistoryDo) Find() ([]*model.AlertHistory, error) {
	result, err := a.DO.Find()
	return result.([]*model.AlertHistory), err
}

func (a alertHistoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AlertHistory, err error) {
	buf := make([]*model.AlertHistory, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a alertHistoryDo) FindInBatches(result *[]*model.AlertHistory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a alertHistoryDo) Attrs(attrs ...field.AssignExpr) IAlertHistoryDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a alertHistoryDo) Assign(attrs ...field.AssignExpr) IAlertHistoryDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a alertHistoryDo) Joins(fields ...field.RelationField) IAlertHistoryDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a alertHistoryDo) Preload(fields ...field.RelationField) IAlertHistoryDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a alertHistoryDo) FirstOrInit() (*model.AlertHistory, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertHistory), nil
	}
}

func (a alertHistoryDo) FirstOrCreate() (*model.AlertHistory, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertHistory), nil
	}
}

func (a alertHistoryDo) FindByPage(offset int, limit int) (result []*model.AlertHistory, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a alertHistoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a alertHistoryDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a alertHistoryDo) Delete(models ...*model.AlertHistory) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *alertHistoryDo) withDO(do gen.Dao) *alertHistoryDo {
	a.DO = *do.(*gen.DO)
	return a
}
