// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package store

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/qinquanliuxiang666/alertmanager/model"
)

func newAlertTemplate(db *gorm.DB, opts ...gen.DOOption) alertTemplate {
	_alertTemplate := alertTemplate{}

	_alertTemplate.alertTemplateDo.UseDB(db, opts...)
	_alertTemplate.alertTemplateDo.UseModel(&model.AlertTemplate{})

	tableName := _alertTemplate.alertTemplateDo.TableName()
	_alertTemplate.ALL = field.NewAsterisk(tableName)
	_alertTemplate.ID = field.NewInt(tableName, "id")
	_alertTemplate.CreatedAt = field.NewTime(tableName, "created_at")
	_alertTemplate.UpdatedAt = field.NewTime(tableName, "updated_at")
	_alertTemplate.DeletedAt = field.NewField(tableName, "deleted_at")
	_alertTemplate.Name = field.NewString(tableName, "name")
	_alertTemplate.Description = field.NewString(tableName, "description")
	_alertTemplate.Template = field.NewString(tableName, "template")
	_alertTemplate.AggregationTemplate = field.NewString(tableName, "aggregation_template")

	_alertTemplate.fillFieldMap()

	return _alertTemplate
}

type alertTemplate struct {
	alertTemplateDo

	ALL                 field.Asterisk
	ID                  field.Int
	CreatedAt           field.Time
	UpdatedAt           field.Time
	DeletedAt           field.Field
	Name                field.String // 模板名称
	Description         field.String
	Template            field.String // 单个告警(Markdown/HTML)模板
	AggregationTemplate field.String // 聚合告警(Markdown/HTML)模板

	fieldMap map[string]field.Expr
}

func (a alertTemplate) Table(newTableName string) *alertTemplate {
	a.alertTemplateDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a alertTemplate) As(alias string) *alertTemplate {
	a.alertTemplateDo.DO = *(a.alertTemplateDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *alertTemplate) updateTableName(table string) *alertTemplate {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewField(table, "deleted_at")
	a.Name = field.NewString(table, "name")
	a.Description = field.NewString(table, "description")
	a.Template = field.NewString(table, "template")
	a.AggregationTemplate = field.NewString(table, "aggregation_template")

	a.fillFieldMap()

	return a
}

func (a *alertTemplate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *alertTemplate) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 8)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["name"] = a.Name
	a.fieldMap["description"] = a.Description
	a.fieldMap["template"] = a.Template
	a.fieldMap["aggregation_template"] = a.AggregationTemplate
}

func (a alertTemplate) clone(db *gorm.DB) alertTemplate {
	a.alertTemplateDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a alertTemplate) replaceDB(db *gorm.DB) alertTemplate {
	a.alertTemplateDo.ReplaceDB(db)
	return a
}

type alertTemplateDo struct{ gen.DO }

type IAlertTemplateDo interface {
	gen.SubQuery
	Debug() IAlertTemplateDo
	WithContext(ctx context.Context) IAlertTemplateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAlertTemplateDo
	WriteDB() IAlertTemplateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAlertTemplateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAlertTemplateDo
	Not(conds ...gen.Condition) IAlertTemplateDo
	Or(conds ...gen.Condition) IAlertTemplateDo
	Select(conds ...field.Expr) IAlertTemplateDo
	Where(conds ...gen.Condition) IAlertTemplateDo
	Order(conds ...field.Expr) IAlertTemplateDo
	Distinct(cols ...field.Expr) IAlertTemplateDo
	Omit(cols ...field.Expr) IAlertTemplateDo
	Join(table schema.Tabler, on ...field.Expr) IAlertTemplateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAlertTemplateDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAlertTemplateDo
	Group(cols ...field.Expr) IAlertTemplateDo
	Having(conds ...gen.Condition) IAlertTemplateDo
	Limit(limit int) IAlertTemplateDo
	Offset(offset int) IAlertTemplateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAlertTemplateDo
	Unscoped() IAlertTemplateDo
	Create(values ...*model.AlertTemplate) error
	CreateInBatches(values []*model.AlertTemplate, batchSize int) error
	Save(values ...*model.AlertTemplate) error
	First() (*model.AlertTemplate, error)
	Take() (*model.AlertTemplate, error)
	Last() (*model.AlertTemplate, error)
	Find() ([]*model.AlertTemplate, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AlertTemplate, err error)
	FindInBatches(result *[]*model.AlertTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AlertTemplate) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAlertTemplateDo
	Assign(attrs ...field.AssignExpr) IAlertTemplateDo
	Joins(fields ...field.RelationField) IAlertTemplateDo
	Preload(fields ...field.RelationField) IAlertTemplateDo
	FirstOrInit() (*model.AlertTemplate, error)
	FirstOrCreate() (*model.AlertTemplate, error)
	FindByPage(offset int, limit int) (result []*model.AlertTemplate, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAlertTemplateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a alertTemplateDo) Debug() IAlertTemplateDo {
	return a.withDO(a.DO.Debug())
}

func (a alertTemplateDo) WithContext(ctx context.Context) IAlertTemplateDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a alertTemplateDo) ReadDB() IAlertTemplateDo {
	return a.Clauses(dbresolver.Read)
}

func (a alertTemplateDo) WriteDB() IAlertTemplateDo {
	return a.Clauses(dbresolver.Write)
}

func (a alertTemplateDo) Session(config *gorm.Session) IAlertTemplateDo {
	return a.withDO(a.DO.Session(config))
}

func (a alertTemplateDo) Clauses(conds ...clause.Expression) IAlertTemplateDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a alertTemplateDo) Returning(value interface{}, columns ...string) IAlertTemplateDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a alertTemplateDo) Not(conds ...gen.Condition) IAlertTemplateDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a alertTemplateDo) Or(conds ...gen.Condition) IAlertTemplateDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a alertTemplateDo) Select(conds ...field.Expr) IAlertTemplateDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a alertTemplateDo) Where(conds ...gen.Condition) IAlertTemplateDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a alertTemplateDo) Order(conds ...field.Expr) IAlertTemplateDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a alertTemplateDo) Distinct(cols ...field.Expr) IAlertTemplateDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a alertTemplateDo) Omit(cols ...field.Expr) IAlertTemplateDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a alertTemplateDo) Join(table schema.Tabler, on ...field.Expr) IAlertTemplateDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a alertTemplateDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAlertTemplateDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a alertTemplateDo) RightJoin(table schema.Tabler, on ...field.Expr) IAlertTemplateDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a alertTemplateDo) Group(cols ...field.Expr) IAlertTemplateDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a alertTemplateDo) Having(conds ...gen.Condition) IAlertTemplateDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a alertTemplateDo) Limit(limit int) IAlertTemplateDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a alertTemplateDo) Offset(offset int) IAlertTemplateDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a alertTemplateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAlertTemplateDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a alertTemplateDo) Unscoped() IAlertTemplateDo {
	return a.withDO(a.DO.Unscoped())
}

func (a alertTemplateDo) Create(values ...*model.AlertTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a alertTemplateDo) CreateInBatches(values []*model.AlertTemplate, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a alertTemplateDo) Save(values ...*model.AlertTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a alertTemplateDo) First() (*model.AlertTemplate, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertTemplate), nil
	}
}

func (a alertTemplateDo) Take() (*model.AlertTemplate, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertTemplate), nil
	}
}

func (a alertTemplateDo) Last() (*model.AlertTemplate, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertTemplate), nil
	}
}

func (a alertTemplateDo) Find() ([]*model.AlertTemplate, error) {
	result, err := a.DO.Find()
	return result.([]*model.AlertTemplate), err
}

func (a alertTemplateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AlertTemplate, err error) {
	buf := make([]*model.AlertTemplate, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a alertTemplateDo) FindInBatches(result *[]*model.AlertTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a alertTemplateDo) Attrs(attrs ...field.AssignExpr) IAlertTemplateDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a alertTemplateDo) Assign(attrs ...field.AssignExpr) IAlertTemplateDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a alertTemplateDo) Joins(fields ...field.RelationField) IAlertTemplateDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a alertTemplateDo) Preload(fields ...field.RelationField) IAlertTemplateDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a alertTemplateDo) FirstOrInit() (*model.AlertTemplate, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertTemplate), nil
	}
}

func (a alertTemplateDo) FirstOrCreate() (*model.AlertTemplate, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertTemplate), nil
	}
}

func (a alertTemplateDo) FindByPage(offset int, limit int) (result []*model.AlertTemplate, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a alertTemplateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a alertTemplateDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a alertTemplateDo) Delete(models ...*model.AlertTemplate) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *alertTemplateDo) withDO(do gen.Dao) *alertTemplateDo {
	a.DO = *do.(*gen.DO)
	return a
}
