// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/qinquanliuxiang666/alertmanager/base/app"
	"github.com/qinquanliuxiang666/alertmanager/base/data"
	"github.com/qinquanliuxiang666/alertmanager/base/middleware"
	"github.com/qinquanliuxiang666/alertmanager/base/router"
	"github.com/qinquanliuxiang666/alertmanager/base/server"
	"github.com/qinquanliuxiang666/alertmanager/controller"
	"github.com/qinquanliuxiang666/alertmanager/pkg/casbin"
	"github.com/qinquanliuxiang666/alertmanager/pkg/feishu"
	"github.com/qinquanliuxiang666/alertmanager/pkg/jwt"
	"github.com/qinquanliuxiang666/alertmanager/pkg/local_cache"
	"github.com/qinquanliuxiang666/alertmanager/pkg/oauth"
	"github.com/qinquanliuxiang666/alertmanager/service/v1"
	"github.com/qinquanliuxiang666/alertmanager/store"
)

// Injectors from wire.go:

func InitApplication() (*app.Application, func(), error) {
	client, err := data.NewRDB()
	if err != nil {
		return nil, nil, err
	}
	cacheStore, cleanup, err := store.NewCacheStore(client)
	if err != nil {
		return nil, nil, err
	}
	generateToken, err := jwt.NewGenerateToken()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	oAuth2, err := oauth.NewOAuth2()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	cacher := localcache.NewCacher(oAuth2)
	userServicer := v1.NewUserService(cacheStore, generateToken, oAuth2, cacher)
	userController := controller.NewUserController(userServicer)
	db, cleanup2, err := data.NewDB()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	enforcer, err := casbin.NewEnforcer(db)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	casbinManager := casbin.NewCasbinManager(enforcer)
	roleServicer := v1.NewRoleService(casbinManager)
	roleController := controller.NewRoleController(roleServicer)
	apiServicer := v1.NewApiServicer()
	apiController := controller.NewApiController(apiServicer)
	feishuer := feishu.NewFeiShu()
	alertsServicer := v1.NewAlertsServicer(cacheStore, feishuer)
	alertManagerController := controller.NewAlertManagerController(alertsServicer)
	authChecker := casbin.NewAuthChecker(enforcer)
	middlewareMiddleware := middleware.NewMiddleware(generateToken, authChecker, cacheStore)
	alertTemplateServicer := v1.NewAlertTemplateServicer(cacheStore)
	alertTemplateController := controller.NewAlertTemplateController(alertTemplateServicer)
	alertChannelServicer := v1.NewChannelServicer(cacheStore)
	alertChannelController := controller.NewAlertChannelController(alertChannelServicer)
	alertHistoryServicer := v1.NewHistoryServicer(cacheStore)
	alertHistoryController := controller.NewAlertHistoryController(alertHistoryServicer)
	routerRouter := router.NewRouter(userController, roleController, apiController, alertManagerController, middlewareMiddleware, alertTemplateController, alertChannelController, alertHistoryController)
	engine, err := server.NewHttpServer(routerRouter)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	application := app.NewApplication(engine, cacheStore, feishuer)
	return application, func() {
		cleanup2()
		cleanup()
	}, nil
}
